### ISSUE TITLE
GitHub page

### ISSUE THREAD

**Issue by adrianpietka** [larmo-hub/larmo-server#31]
Create a GitHub Page for project.

**Comment by zeulus** [comment]
Pedro, can you prepare the github.io page as per your design? :)

**Comment by dalailomo** [comment]
Sure! :)

**Comment by dalailomo** [comment]
Hey guys, I have the Github page ready to be pushed, which branch can I use?

**Comment by zeulus** [comment]
That should be pushed to `gh-pages` branch, see https://help.github.com/articles/creating-project-pages-manually/

**Comment by adrianpietka** [comment]
Hi guys.

I move github-page of Larmo to http://larmo.org :-)
