### ISSUE TITLE
GUI Improvements and new features

### ISSUE THREAD

**Issue by dalailomo** [larmo-hub/larmo-server#69]
## Messages
- ~~Format messages to display newlines correctly~~ (https://github.com/adrianpietka/larmo/pull/71)
- Truncate long messages and create a 'View more' button
- Do not display emails in messages

## Filters
- ~~Instead of a drop-down, make a icon list with all available sources. This will allow the users to select which sources they want to see at the same time~~ (https://github.com/adrianpietka/larmo/pull/74)

## General
- Disable zoom feature in mobile devices
- Display a *Scroll to top* button

**Comment by mejt** [comment]
https://github.com/larmo-hub/larmo-webapp
