### ISSUE TITLE
Title for icons on webapp

### ISSUE THREAD

**Issue by zeulus** [larmo-hub/larmo-server#76]
Hey, we would need something that would explain what those icons mean. Is it possible to add some title or something that will show on mouse over?

**Comment by dalailomo** [comment]
Yes, sure. Maybe a tooltip on hover (and on long press in mobile devices).

Like this ones http://tympanus.net/TipsTricks/CSS3Tooltips/

**Comment by mejt** [comment]
In my opinion bar with icons isn't good designed. I think in future we'll extend our filters (like search by word, search in date range) and this bar should be more adaptive. Brand icons should be part of filters instead main functionality this bar.

**Comment by zeulus** [comment]
Good point @mejt . 

@dalailomo  - at the moment we don't have rest of functionality, but could you add just simple search box for text search? date range might be more complicated and not very often used, so let's skip that for now.

**Comment by dalailomo** [comment]
@mejt is right about that the brand icons should be part of filters, but is not a design issue, and I already though about that. I have some ideas to fix that but I need to work on them.

@zeulus I can add only a text search box, or if you prefer, I can come with a complete solution for search by word, search in a date range, filter by sources, ect...

**Comment by zeulus** [comment]
Whatever you prefer and have time for it, @dalailomo  :)

**Comment by dalailomo** [comment]
Cool :)

Any ideas are welcome :D

**Comment by mejt** [comment]
Come on to [issues list](https://github.com/adrianpietka/larmo/issues) and look at search box. Huge text box and button with more filters. I think it is good way because we don't know how many we'll support services in future.

**Comment by mejt** [comment]
It is discussion for another repository (https://github.com/larmo-hub/larmo-webapp).
